name: Daily CI
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [daily]
jobs:
  release:
    name: Daily
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Fetch daily data
        run: npm run daily
        env:
          GOODREADS_USER_ID: ${{ secrets.GOODREADS_USER_ID }}
          GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
          GOODREADS_SECRET: ${{ secrets.GOODREADS_SECRET }}
          GOODREADS_CALLBACK_URL: ${{ secrets.GOODREADS_CALLBACK_URL }}
          POCKET_CASTS_USERNAME: ${{ secrets.POCKET_CASTS_USERNAME }}
          POCKET_CASTS_PASSWORD: ${{ secrets.POCKET_CASTS_PASSWORD }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_CALLBACK_URL: ${{ secrets.SPOTIFY_CALLBACK_URL }}
          SPOTIFY_ACCESS_TOKEN: ${{ secrets.SPOTIFY_ACCESS_TOKEN }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          RESCUETIME_API_KEY: ${{ secrets.RESCUETIME_API_KEY }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_SHARED_SECRET: ${{ secrets.LASTFM_SHARED_SECRET }}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
          CLOCKIFY_WORKSPACE_ID: ${{ secrets.CLOCKIFY_WORKSPACE_ID }}
          CLOCKIFY_USER_ID: ${{ secrets.CLOCKIFY_USER_ID }}
          CLOCKIFY_API_KEY: ${{ secrets.CLOCKIFY_API_KEY }}
          GOOGLE_FIT_CLIENT_ID: ${{ secrets.GOOGLE_FIT_CLIENT_ID }}
          GOOGLE_FIT_CLIENT_SECRET: ${{ secrets.GOOGLE_FIT_CLIENT_SECRET }}
          GOOGLE_FIT_ACCESS_TOKEN: ${{ secrets.GOOGLE_FIT_ACCESS_TOKEN }}
          GOOGLE_FIT_REFRESH_TOKEN: ${{ secrets.GOOGLE_FIT_REFRESH_TOKEN }}
          OURA_PERSONAL_ACCESS_TOKEN: ${{ secrets.OURA_PERSONAL_ACCESS_TOKEN }}
      - name: Generate summaries
        run: npm run summary
      - name: Commit new data
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: ":card_file_box: Update daily life data [skip ci]"
          commit_user_name: Stethoscoper
          commit_user_email: stethoscope-js@anandchowdhary.com
          commit_author: Stethoscoper <stethoscope-js@anandchowdhary.com>
